### ISSUE TITLE
Wrong architecture for Android

### ISSUE THREAD

**Issue by tdauth** [LaurentGomila/qt-android-cmake#11]
First of all, great project. I've been looking for something like this all day.
However I am getting an error since it expects the architecture i686 which I did not specify. It should rather use the directory "x86-4.9" from the specified architecture in the toolchains path. As you can see I specified -DANDROID_ABI="x86".
http://stackoverflow.com/questions/38945267/addqtandroidapk-detects-wrong-target-architecture

Maybe I did something wrong in my configuration. How is the path determined and which variables do I have to set? I am trying to figure out if this is a bug or I forgot something.

**Comment by tdauth** [comment]
Seems like https://github.com/LaurentGomila/qt-android-cmake/pull/10 fixes my problems, so you might merge it into the master.

**Comment by LaurentGomila** [comment]
Thanks for your feedback. I'll try to take care of #10.

**Comment by LaurentGomila** [comment]
#10 is now closed, but the part that fixes your problem is not merged (unles it was the minSdkVersion thing, which I doubt). See the comments for more details.
