### ISSUE TITLE
Add to the documentation that the version of a target has to be specified

### ISSUE THREAD

**Issue by tdauth** [LaurentGomila/qt-android-cmake#12]
I had to use set_property(TARGET mytarget PROPERTY VERSION "1"). Otherwise the version in the manifest was empty which led to an error.

**Comment by LaurentGomila** [comment]
True, I'll add something to the doc, and maybe also add a check in the CMake code directly.

**Comment by LaurentGomila** [comment]
Fixed in 365a294
