### ISSUE TITLE
Could not get armeabi-v7a and x86 to build.

### ISSUE THREAD

**Issue by mbp-2016** [LaurentGomila/qt-android-cmake#13]
First of all thanks for the work.

Using android-ndk-r10.

For armabi-v7a e.g. strip command is:

C:\work\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-strip.exe

For x86:

C:\work\android-ndk-r13b\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-strip.exe

Note how in the first case the folder arm-linux-andoideabi-4.9 and arm-linux-androideabi-strip.exe
have matching roots ("arm-linux-androideabi"). For x86 the roots are "x86" and "i686-linux-android" i.e. different. 

Oddly enough CMAKE_STRIP is set correctly in both cases. However, when trying to build for x86 got the warning:

Command does not exist: C:/work/android-ndk-r10/toolchains/i686-linux-android-4.8/prebuilt/windows-x86_64/bin/i686-linux-android-strip.exe

Fix is to add an additional define "ANDROID_TOOLCHAIN_PREFIX" which the user can set (for x86) or let it default to ANDROID_TOOLCHAIN_MACHINE_NAME for e,g, armeabi-v7a.

Have attached the two files I changed. Tested for x86 and armeabi-v7a only.

[android.toolchain.zip](https://github.com/LaurentGomila/qt-android-cmake/files/648707/android.toolchain.zip)
[qtdeploy.json.zip](https://github.com/LaurentGomila/qt-android-cmake/files/648708/qtdeploy.json.zip)

**Comment by LaurentGomila** [comment]
The latest update (to use the NDK toolchain) should solve this problem. Don't hesitate to reopen this issue if it doesn't.
