### ISSUE TITLE
Gradle/Qt Android deployment removes the folder "build dir/res"

### ISSUE THREAD

**Issue by tdauth** [LaurentGomila/qt-android-cmake#16]
Sorry to bother with another problem but the latest version seems to delete and renew the folder "builddir/res" of my CMake project.
It creates the folder "builddir/res/values" where it creates the single file libs.xml.
The problem is that I copy some files like drawables and string files into this directory before building the APK which are removed by the Qt deployment for Android.
This might be done by Gradle (I used ant before with the old version).
How can I prevent the deletion of the folder or copy files into the directory before the APK is finally built.
It requires the drawable and strings as application icon and name.

**Comment by LaurentGomila** [comment]
I have no idea, you'll have to investigate this issue yourself.

**Comment by tdauth** [comment]
Here is some log output which shows that my :
```
/mnt/ntfs/Qt/5.9.2/android_armv7/bin/androiddeployqt --verbose --output /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a --input /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/qtdeploy.json --gradle --android-platform android-26 --release --sign /home/tamino/Dokumente/Projekte/fairytale/my-release-key.keystore gustavsfairyland --tsa http://timestamp.digicert.com
Warning: Android platform 'android-26' does not exist in SDK.
Generating Android Package
  Input file: /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/qtdeploy.json
  Output directory: /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/
  Application binary: /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/libgustavsfairyland.so
  Android build platform: android-26
  Install to device: No
Delete missing files /mnt/ntfs/Qt/5.9.2/android_armv7/src/android/templates/res /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/res
drawable not found in /mnt/ntfs/Qt/5.9.2/android_armv7/src/android/templates/res, removing it.
Delete missing files /mnt/ntfs/Qt/5.9.2/android_armv7/src/android/templates/res/values /home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/res/values
values-de not found in /mnt/ntfs/Qt/5.9.2/android_armv7/src/android/templates/res, removing it.
Copying Android package template.
```
I tried to remove the "res" folder in the "build.gradle" file but it did not change anything.
"/home/tamino/Dokumente/Projekte/fairytale/buildandroidarmeabi-v7a/" is my build directory.
As  you can see here: http://code.qt.io/cgit/qt/qttools.git/tree/src/androiddeployqt/main.cpp
androiddeployqt seems to clean the top level directories (function cleanAndroidFiles()).
It deletes all files which do not exist in the "android-package-source-directory" directory but in the target dir?
This is set to QT_ANDROID_APP_PACKAGE_SOURCE_ROOT which is the "package" directory in the build directory.
Therefore, do I have to copy my resource files into the package directory???

**Comment by LaurentGomila** [comment]
> Therefore, do I have to copy my resource files into the package directory???

I remember now, indeed, that's what you're supposed to do. Everything that is in the "package" directory will be copied over to the bin directory by the Qt tool.
