### ISSUE TITLE
How to remove dependency to ministro system

### ISSUE THREAD

**Issue by benapetr** [LaurentGomila/qt-android-cmake#19]
When I compile my app using this toolchain, it always make it dependent on ministro, asking me to download all Qt libraries through it. In qtcreator, there is an option to disable this, but how I do that in cmake option?

**Comment by LaurentGomila** [comment]
It shouldn't. Which version of Qt are you using?

**Comment by benapetr** [comment]
5.6.3, any newer version of Qt doesn't work with this toolchain, because of this bug https://stackoverflow.com/questions/38027292/configure-a-qt5-5-7-application-for-android-with-cmake

**Comment by LaurentGomila** [comment]
From the `androiddeployqt` tool help:

```
 --deployment <mechanism>: Supported deployment mechanisms:
       bundled (default): Include Qt files in stand-alone package.
       ministro: Use the Ministro service to manage Qt files.
       debug: Copy Qt files to device for quick debugging.
```

qt-android-cmake doesn't specify the `--deployment` option, so you should get the default behavior which is "bundled" and not "ministro". Make sure that you haven't some global configuration that would override this behavior.

> any newer version of Qt doesn't work with this toolchain, because of this bug 

Have you tried the workaround? It's just one line to touch in Qt's CMake files.

**Comment by benapetr** [comment]
I tried to run androiddeployqt with --deployment debug and result was again that it requires ministro. I will try to explicitly tell it "bundled", but from debug logs, it's obvious that the tool was not run with any --deployment option, so default should have been chosen.

No I haven't tried the workaround.

**Comment by benapetr** [comment]
I can try with newer Qt, but not sure if it would friend with very old SDK and NDK I am using now, because this toolchain doesn't work with newer NDK and SDK (see https://github.com/LaurentGomila/qt-android-cmake/issues/17)
