### ISSUE TITLE
The CMAKE_FORCE_CXX_COMPILER macro is deprecated

### ISSUE THREAD

**Issue by pepijndevos** [LaurentGomila/qt-android-cmake#23]
When using your beautiful and indispensable toolchain, I get the following warnings.
```
CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/rove/code/qt-android-cmake/toolchain/android.toolchain.cmake:1123 (CMAKE_FORCE_C_COMPILER)
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:91 (include)
  CMakeLists.txt:3 (project)


CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/rove/code/qt-android-cmake/toolchain/android.toolchain.cmake:1135 (CMAKE_FORCE_CXX_COMPILER)
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:91 (include)
  CMakeLists.txt:3 (project)

```

Later, when using the APK macro, I also get

```
CMake Deprecation Warning at /home/rove/code/qt-android-cmake/AddQtAndroidApk.cmake:2 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  src/CMakeLists.txt:74 (include)
```

These seem to be harmless for now, but might break stuff in the future.
So far my experience with Android has been that if  you use anything too new or too old, everything breaks.

**Comment by LaurentGomila** [comment]
Yes, there are many issues with this old toolchain, I (or some motivated developer) should update it, or update the main script to use the toolchains provided in the NDK.

**Comment by alvarobasi** [comment]
Yeah, I intended to open a new thread commenting this issue until I saw you already talked about it. As it is the only great functional tool I know it'd be very convenient to update it according to the new api-level.h location and format used in newer versions of NDK ;). Thank you very much for this tool! As pepijndevos said, it is indispensable.

**Comment by LaurentGomila** [comment]
The latest update (to use the NDK toolchain) should solve this problem. Don't hesitate to reopen this issue if it doesn't.
