### ISSUE TITLE
Wrong location might be chosen for dependencies if building "Debug" configuration.

### ISSUE THREAD

**Issue by nohype** [LaurentGomila/qt-android-cmake#26]
Hi,

first of all, thank you for this project. It's great and has helped me a lot already!

One issue that came up though is the use of the LOCATION property for dependency targets (DEPENDS <...>), which is not guaranteed to hold the release binary (LOCATION_RELEASE). Thus, for some library targets, the debug version ends up in the APK with a release build of the app. (Which makes the app not run properly on a device.)

Side note: I've fixed it using generator expressions which will be evaluated at build time depending on the current build configuration. I'll see if i can get a pull request together.

**Comment by LaurentGomila** [comment]
Should be fixed with #25.
