### ISSUE TITLE
Depreciation warning

### ISSUE THREAD

**Issue by Gibbz** [LaurentGomila/qt-android-cmake#29]
The following warning with the cmake script

> CMake Deprecation Warning at android/AddQtAndroidApk.cmake:2 (cmake_policy):
>   The OLD behavior for policy CMP0026 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.

**Comment by LaurentGomila** [comment]
Should be fixed with #25.
