### ISSUE TITLE
Build failures with latest master

### ISSUE THREAD

**Issue by dirkhh** [LaurentGomila/qt-android-cmake#33]
When merging commit https://github.com/LaurentGomila/qt-android-cmake/commit/78f06f318cf40bf50307cc6b7c28b390308caa1a you introduced a new check for a variable `PROJECT_VERSION` that isn't referenced anywhere else. If that variable isn't set, a build will fail with
```
CMake Error at /__w/***/qt-android-cmake/AddQtAndroidApk.cmake:106 (if):
if given arguments:
     "STREQUAL" ""
```
That seems suboptimal.

**Comment by LaurentGomila** [comment]
This new logic was not fully tested, so thanks for your feedback.

`PROJECT_VERSION` is a CMake variable that contains the version defined in the current project scope.

So either you're using the tool before a call to `project()`, or you didn't pass a `VERSION` argument to it. I'll fix it by first testing if `PROJECT_VERSION` is defined.

**Comment by LaurentGomila** [comment]
Should be ok now.

Thanks for your feedback!
