### ISSUE TITLE
ndk_gdb feature

### ISSUE THREAD

**Issue by yamsu** [LaurentGomila/qt-android-cmake#36]
How can one get ndk_gdb to perform debugging on an android target? As per the ndk_gdb online help it requires the build process to use ndk_build script.

Is there any alternative way to perform breakpoint debug. Qt creator has a few options also but I do not want to rely on it for compilation.

I have qt cpp code with qml frontend.

**Comment by LaurentGomila** [comment]
I have no idea, I'm sorry. I usually debug my Android apps on my desktop PC (most of them are cross-platform), and for Android specific stuff, I use the SDK monitor app and debug logs.

You should ask somewhere else, like on stackoverflow. If you find an answer, please keep us informed 👍
