### ISSUE TITLE
Add a way for the user to provide a custom gradle.build.in

### ISSUE THREAD

**Issue by OlivierLDff** [LaurentGomila/qt-android-cmake#40]
Since different version of qt use different version of gradle in the `src/` folder, would it be possible to use our own `gradle.build.in` script.

* Qt5.13: `'com.android.tools.build:gradle:3.2.0'`
* Qt5.14: `'com.android.tools.build:gradle:3.5.0'`
* Qt5.15: `'com.android.tools.build:gradle:3.6.0'`

I tried just to update the script to 3.6 but build break with Qt 5.13.

Would you consider a PR that allow user to provide a `build.gradle.in` in the same way as `AndroidManifest.xml.in` ?

**Comment by LaurentGomila** [comment]
Before anyone submits a PR, I'd have to investigate this, as right now I have no idea how it works and how it should be handled.

**Comment by Dushistov** [comment]
I need this too, but for different reason. I have to modifying   `aaptOptions`
```
aaptOptions {
         noCompress 'rcc'
+        noCompress 'txt', 'bin', 'html', 'png', 'json', 'mwm', 'ttf', 'sdf', 'ui', 'config', 'csv', 'spv'
```

It would be nice if `build.gradle.in` works in the same way as AndroidManifest.xml.in
User will provide `PACKAGE_SOURCES`
```
add_qt_android_apk(
       ...
      PACKAGE_SOURCES ${PROJECT_SOURCE_DIR}/platforms/android
```
and if there is `build.gradle.in` cmake will use it instead of default one.

**Comment by LaurentGomila** [comment]
Would you like to contribute with a PR?

**Comment by Dushistov** [comment]
@LaurentGomila  I created #45

**Comment by LaurentGomila** [comment]
Thanks!
