### ISSUE TITLE
need option to unbind java release mode and C++ releasemode

### ISSUE THREAD

**Issue by Dushistov** [LaurentGomila/qt-android-cmake#44]
My project heavy enough to run it with `CMAKE_BUILD_TYPE=Debug`,
slow start, slow redraw and so on. So everyday I use `RelWithDebInfo` mode,
but at the same time I need apk build in debug mode to run it via IDE without any issues.
So I  need some new option to tell `qt-android-cmake` that I need debug mode anyway,
even if `CMAKE_BUILD_TYPE != Debug`:
```
if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT ARG_KEYSTORE)
        set(QT_ANDROID_BUILD_TYPE --debug)
    else()
        set(QT_ANDROID_BUILD_TYPE --release)
    endif()
```

**Comment by LaurentGomila** [comment]
Yes, that could be helpful.

A good solution would be to add a CMake option, such as `APK_BUILD_TYPE`. If omitted, the current logic applies (so that we keep the same behavior by default). If set, it overrides the choice.

Or should we just map `RelWithDebInfo` to a debug APK?

**Comment by Dushistov** [comment]
I add `APK_BUILD_TYPE` into #46 , variants: debug, release, auto or empty.
auto or empty = current behavior. I see possibility when you want APK_BUILD_TYPE = release , while CMAKE_BUILD_TYPE = Debug, for example in case you need make release to get more debug info for some nasty crash.

**Comment by LaurentGomila** [comment]
Ok thanks. I'll try to review your PR quickly.
