### ISSUE TITLE
how to change the icon of android app

### ISSUE THREAD

**Issue by e665107** [LaurentGomila/qt-android-cmake#52]
Hi  Friend
         Now, I have adapt your cmake with my own, but I can't change the icon of app.  I  have tried to make a dir named res , and add a icon.png.  Then add the icon attribute to andrioidmainfest.xml. But it can't find it. In the binnary dir, I find the res, but it doesn't have the icon.png, Can you help me? Thanks a lot!

**Comment by LaurentGomila** [comment]
It was a long time ago, so maybe it has changed, but here is how it's done in one of my old projects:

In manifest:
```xml
<application ... android:icon="@drawable/icon">
```

Then, "icon.png" is under "res/drawable-ldpi".

**Comment by e665107** [comment]
Thank you for your instant reply! I have solved this problem by adding the   PACKAGE_SOURCES ${CMAKE_CURRENT_LIST_DIR}.
