### ISSUE TITLE
linking error if not specifying stand-alone toolchain

### ISSUE THREAD

**Issue by klaussnd** [LaurentGomila/qt-android-cmake#6]
When deploying as documented, I get the linking error
/usr/local/Android/android-ndk-r10e/toolchains/arm-linux-
androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-
androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot open 
crtbegin_so.o: No such file or directory

If I create a stand-alone toolchain and add
-DANDROID_STANDALONE_TOOLCHAIN=<path_to_standalone_toolchain>, the issue is solved. To me this seems very odd, IMHO you should not need both the NDK and a stand-alone toolchain, one of them should be sufficient. Any explanation?

By the way, it would be cool if qtdeploy would also support a stand-alone toolchain, so that the full NDK is no longer required.

**Comment by LaurentGomila** [comment]
You're the first one so far to face such a problem. So I'd say that there's an issue with your environment.

**Comment by LaurentGomila** [comment]
This issue lacks more feeback, so I'm closing it for now.
