### ISSUE TITLE
Application name setting is not working

### ISSUE THREAD

**Issue by paines** [LaurentGomila/qt-android-cmake#9]
Setting QT_ANDROID_APP_NAME from CMakeLists.txt isn't working for some reason.

**Comment by LaurentGomila** [comment]
The script overwrites it. Don't try undocumented things.

**Comment by paines** [comment]
Sorry for my ignorance, does that mean this isn't working for now, or am I doing it wrong ? Thanks!

**Comment by LaurentGomila** [comment]
"What" is not working? The documentation never mentions QT_ANDROID_APP_NAME, you're not supposed to do anything with it.

Just follow the public documentation and everything will be fine.

**Comment by paines** [comment]
Changing the name of the application does not work. The documentation says 

```
add_qt_android_apk(my_app_apk my_app
    NAME "My App"
)
```

However, this is not working, so I thought to use the parameter QT_ANDROID_APP_NAME which qtdeploy.json.in is referencing, but this also does not work. Besides that, everything else works fine. Sorry for the confusion, and thanks.

**Comment by LaurentGomila** [comment]
Oh, ok. Your original description was terribly confusing :stuck_out_tongue:

This is supposed to work. What app name do you get instead of "My App"? Do you use a custom manifest?

**Comment by paines** [comment]
I am getting QtApp- as prefix and then + debug.apk, debug-unaligend.apk, and release-unsigned.apk. And no I am not using a custom Manifest. I am using the one provided by qt-android-cmake.

**Comment by LaurentGomila** [comment]
This is normal. The _file_ name has nothing to do with the _app_ name.
